/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CRM;

import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brij kishore sharma
 */
public class Interactions extends javax.swing.JFrame {

    /**
     * Creates new form Interactions
     */
    public Interactions() {
         super("INTERACTIONS");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        showbtn = new javax.swing.JButton();
        delbtn = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addinteractions = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox<>();
        cb2 = new javax.swing.JComboBox<>();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 150));
        setMaximumSize(new java.awt.Dimension(810, 525));
        setMinimumSize(new java.awt.Dimension(810, 525));
        setPreferredSize(new java.awt.Dimension(810, 525));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb1.setBackground(new java.awt.Color(0, 0, 0));
        tb1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        tb1.setForeground(new java.awt.Color(255, 255, 255));
        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Interaction ID", "Date (YYYYMMDD)", "Lead ID", "By Which Means ", "Potential"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tb1.getTableHeader().setReorderingAllowed(false);
        tb1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1);
        if (tb1.getColumnModel().getColumnCount() > 0) {
            tb1.getColumnModel().getColumn(0).setResizable(false);
            tb1.getColumnModel().getColumn(1).setResizable(false);
            tb1.getColumnModel().getColumn(1).setPreferredWidth(110);
            tb1.getColumnModel().getColumn(2).setResizable(false);
            tb1.getColumnModel().getColumn(3).setResizable(false);
            tb1.getColumnModel().getColumn(3).setPreferredWidth(110);
            tb1.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 220));

        showbtn.setBackground(new java.awt.Color(0, 0, 0));
        showbtn.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        showbtn.setForeground(new java.awt.Color(255, 255, 255));
        showbtn.setText("Show");
        showbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showbtnActionPerformed(evt);
            }
        });
        getContentPane().add(showbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, -1, -1));

        delbtn.setBackground(new java.awt.Color(0, 0, 0));
        delbtn.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        delbtn.setForeground(new java.awt.Color(255, 255, 255));
        delbtn.setText("Delete");
        delbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delbtnActionPerformed(evt);
            }
        });
        getContentPane().add(delbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, -1, -1));

        update.setBackground(new java.awt.Color(0, 0, 0));
        update.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Date(YYYMMDD)");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 160, 50));

        jLabel2.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lead ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 91, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("By which means");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 369, 170, -1));

        addinteractions.setBackground(new java.awt.Color(0, 0, 0));
        addinteractions.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        addinteractions.setForeground(new java.awt.Color(255, 255, 255));
        addinteractions.setText("Add interactions");
        addinteractions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addinteractionsActionPerformed(evt);
            }
        });
        getContentPane().add(addinteractions, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Potential");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 414, 140, -1));

        cb1.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        cb1.setForeground(new java.awt.Color(255, 255, 255));
        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phone ", "Face to Face", "Email", "Social media" }));
        getContentPane().add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 140, 30));

        cb2.setFont(new java.awt.Font("Palatino Linotype", 3, 18)); // NOI18N
        cb2.setForeground(new java.awt.Color(255, 255, 255));
        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Positive", "Negative", "Neutral" }));
        getContentPane().add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 140, 30));
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 150, 40));
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 150, 40));

        jLabel5.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Interaction ID");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 160, -1));

        lb1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lb1.setForeground(new java.awt.Color(255, 255, 255));
        lb1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(lb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 282, 159, 30));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Lucida Sans Typewriter", 3, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CRM/images/60 Vintage Backgrounds Vintage B.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showbtnActionPerformed
        // TODO add your handling code here:
        try{
                connectionclass obj = new connectionclass();
        String q= "Select * from interactions ";
        ResultSet rest= obj.stn.executeQuery(q);
         DefaultTableModel tbModel1 = (DefaultTableModel)tb1.getModel();
            tbModel1.setRowCount(0);
        while (rest.next()){
            String interactionid = String.valueOf(rest.getInt("interactionid"));//conversion due to int value 
            String date = rest.getString("date");
            String leadid = rest.getString("leadid");
            String means = rest.getString("means");
            String potential = rest.getString("potential");
            //string array for store data in jtable
            String tbData[]={interactionid,date,leadid,means,potential};
            DefaultTableModel tbModel = (DefaultTableModel)tb1.getModel();
            //add string array data into table
            tbModel.addRow(tbData);
            }}
                catch(Exception ee){
                    ee.printStackTrace();
                }
    }//GEN-LAST:event_showbtnActionPerformed

    private void addinteractionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addinteractionsActionPerformed
        // TODO add your handling code here:
        String date= tf1.getText();
        String leadid= tf2.getText();
        String means= cb1.getSelectedItem().toString();
        String potential= cb2.getSelectedItem().toString();
        
        if(date.isEmpty() || leadid.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please give some input!");
        }else{
        try{
        connectionclass obj = new connectionclass();
        String q2= "Select * from interactions ";
        String q1= "select 1 from leads where id ='"+leadid+"'";
        String q= "insert into interactions(date,leadid,means,potential) values('"+date+"','"+leadid+"','"+means+"','"+potential+"')";
        int aa = obj.stn.executeUpdate(q);
        ResultSet aa1 = obj.stn.executeQuery(q1);
        if(aa1.next()){
        if(aa==1){
            tf1.setText("");
            tf2.setText("");
            JOptionPane.showMessageDialog(null,"Your data inserted successfully.");
            this.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null, "Please ! Enter carefully.");
        this.setVisible(true);
        }}else{
        JOptionPane.showMessageDialog(null,"Please enter correct Lead ID!");
            this.setVisible(true);
        }
        ResultSet rest= obj.stn.executeQuery(q1);
        while (rest.next()){
            String interactionid1 = String.valueOf(rest.getInt("interactionid"));//conversion due to int value 
            String date1 = rest.getString("date");
            String leadid1 = rest.getString("leadid");
            String means1 = rest.getString("means");
            String potential1 = rest.getString("potential");
            String tbData[]={interactionid1,date1,leadid1,means1,potential1};
            DefaultTableModel tbModel = (DefaultTableModel)tb1.getModel();
            tbModel.setRowCount(0);
            tbModel.addRow(tbData);
        }
        }
        catch(Exception ee){
        ee.printStackTrace();
        }
        }
    }//GEN-LAST:event_addinteractionsActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String date= tf1.getText();
        String leadid= tf2.getText();
        String means= cb1.getSelectedItem().toString();
        String potential=cb2.getSelectedItem().toString();
        if(date.isEmpty()||leadid.isEmpty()){
        JOptionPane.showMessageDialog(null, "Enter values in fields.");
        }else{
        try{
        connectionclass obj = new connectionclass();
        String q1= "Select * from interactions ";
        String q= "update Interactions set date='"+date+"', means= '"+means+"',potential= '"+potential+"' where leadid='"+leadid+"'";
        int aa = obj.stn.executeUpdate(q);
        if(aa==1){
            tf1.setText("");
            tf2.setText(""); 
            JOptionPane.showMessageDialog(null,"Your data updated successfully");
            this.setVisible(true);
        }
        else{
        JOptionPane.showMessageDialog(null, "Please ! Enter carefully");
        this.setVisible(true);
        }
        ResultSet rest= obj.stn.executeQuery(q1);
        while (rest.next()){
            String interactionid1 = String.valueOf(rest.getInt("interactionid"));//conversion due to int value 
            String date1 = rest.getString("date");
            String leadid1 = rest.getString("leadid");
            String means1 = rest.getString("means");
            String potential1 = rest.getString("potential");
            String tbData[]={interactionid1,date1,leadid1,means1,potential1};
            DefaultTableModel tbModel = (DefaultTableModel)tb1.getModel();
            tbModel.setRowCount(0);
            tbModel.addRow(tbData);
        }}
        catch(Exception ee){
        ee.printStackTrace();
        }}
        
    }//GEN-LAST:event_updateActionPerformed

    private void tb1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1MouseClicked
        // TODO add your handling code here:
         DefaultTableModel tbModel = (DefaultTableModel)tb1.getModel();
        int selectedrow = tb1.getSelectedRow();
        lb1.setText(tbModel.getValueAt(selectedrow, 0).toString());
        tf1.setText(tbModel.getValueAt(selectedrow, 1).toString());
        tf2.setText(tbModel.getValueAt(selectedrow, 2).toString());
        cb1.setSelectedItem(tbModel.getValueAt(selectedrow, 3));
        cb2.setSelectedItem(tbModel.getValueAt(selectedrow, 4));
    }//GEN-LAST:event_tb1MouseClicked

    private void delbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delbtnActionPerformed
        // TODO add your handling code here:
        String interactionid= lb1.getText();
        try {
        String q1= "Select * from interactions ";
        connectionclass obj = new connectionclass();
        String q= "delete from interactions where interactionid='"+interactionid+"' ";
        obj.stn.executeUpdate(q);
        JOptionPane.showMessageDialog(null,"Data successfully deleted");
        this.setVisible(true);
        ResultSet rest= obj.stn.executeQuery(q1);
                    DefaultTableModel tbModel1 = (DefaultTableModel)tb1.getModel();
            tbModel1.setRowCount(0);
        while (rest.next()){
            String interactionid1 = String.valueOf(rest.getInt("interactionid"));//conversion due to int value 
            String date1 = rest.getString("date");
            String leadid1 = rest.getString("leadid");
            String means1 = rest.getString("means");
            String potential1 = rest.getString("potential");
            String tbData[]={interactionid1,date1,leadid1,means1,potential1};
            DefaultTableModel tbModel = (DefaultTableModel)tb1.getModel();
            tbModel.addRow(tbData);
        }
        }
        catch(Exception ee){
        ee.printStackTrace();
        }
    }//GEN-LAST:event_delbtnActionPerformed
private JFrame frame;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame = new JFrame("Cancel");
       if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to cancel","Cancel",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
            new Mainpg().setVisible(true);
            this.setVisible(false);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addinteractions;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton delbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JButton showbtn;
    private javax.swing.JTable tb1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
